namespace TRRCMS.Application.Import.Models;

/// <summary>
/// Represents the parsed manifest from a .uhc SQLite container.
/// The manifest table in the .uhc file contains package metadata,
/// content counts, vocabulary versions, and security checksums.
/// 
/// Referenced in UC-003 Stage 2 — S12 (Verify Package Integrity).
/// </summary>
public class ManifestData
{
    // ==================== PACKAGE IDENTITY ====================

    /// <summary>
    /// Unique package GUID generated by the mobile app at export time.
    /// Used for idempotency: if a package with this ID already exists, reject as duplicate.
    /// </summary>
    public Guid PackageId { get; set; }

    /// <summary>
    /// Schema version of the .uhc container format.
    /// Used for backward-compatible parsing.
    /// </summary>
    public string SchemaVersion { get; set; } = string.Empty;

    /// <summary>
    /// UTC timestamp when the package was created on the tablet.
    /// </summary>
    public DateTime CreatedUtc { get; set; }

    // ==================== DEVICE / APP METADATA ====================

    /// <summary>
    /// Unique device identifier of the tablet that created the package.
    /// </summary>
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// Mobile app version string (e.g. "2.3.1").
    /// </summary>
    public string AppVersion { get; set; } = string.Empty;

    /// <summary>
    /// Field collector user ID who exported the package.
    /// </summary>
    public Guid ExportedByUserId { get; set; }

    /// <summary>
    /// UTC timestamp when the package was exported from the tablet.
    /// </summary>
    public DateTime ExportedDateUtc { get; set; }

    // ==================== VOCABULARY VERSIONS ====================

    /// <summary>
    /// Dictionary of vocabulary domain → semver version.
    /// Example: { "ownership_type": "1.2.0", "document_type": "2.1.3" }
    /// Used for vocabulary compatibility checking (FR-D-3).
    /// </summary>
    public Dictionary<string, string> VocabVersions { get; set; } = new();

    /// <summary>
    /// Form schema version used by the mobile app.
    /// </summary>
    public string FormSchemaVersion { get; set; } = string.Empty;

    // ==================== SECURITY ====================

    /// <summary>
    /// SHA-256 checksum of the data tables (excluding the manifest itself).
    /// Used for integrity verification.
    /// </summary>
    public string Checksum { get; set; } = string.Empty;

    /// <summary>
    /// Optional digital signature of the package.
    /// Null if the mobile app does not support signing.
    /// </summary>
    public string? DigitalSignature { get; set; }

    // ==================== CONTENT COUNTS ====================

    /// <summary>Number of surveys in the package.</summary>
    public int SurveyCount { get; set; }

    /// <summary>Number of buildings in the package.</summary>
    public int BuildingCount { get; set; }

    /// <summary>Number of property units in the package.</summary>
    public int PropertyUnitCount { get; set; }

    /// <summary>Number of persons in the package.</summary>
    public int PersonCount { get; set; }

    /// <summary>Number of households in the package.</summary>
    public int HouseholdCount { get; set; }

    /// <summary>Number of person-property relations in the package.</summary>
    public int RelationCount { get; set; }

    /// <summary>Number of claims in the package.</summary>
    public int ClaimCount { get; set; }

    /// <summary>Number of evidence/document files in the package.</summary>
    public int DocumentCount { get; set; }

    /// <summary>Total attachment size in bytes.</summary>
    public long TotalAttachmentSizeBytes { get; set; }

    // ==================== COMPUTED ====================

    /// <summary>
    /// Total record count across all entity types.
    /// </summary>
    public int TotalRecordCount =>
        SurveyCount + BuildingCount + PropertyUnitCount + PersonCount +
        HouseholdCount + RelationCount + ClaimCount + DocumentCount;
}
