using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TRRCMS.Application.Common.Interfaces;
using TRRCMS.Application.Import.Dtos;
using TRRCMS.Application.Import.Models;
using TRRCMS.Domain.Entities;
using TRRCMS.Domain.Entities.Staging;
using TRRCMS.Domain.Enums;

namespace TRRCMS.Infrastructure.Services;

/// <summary>
/// Implements <see cref="ICommitService"/> — commits approved staging data to production.
///
/// Commit order matters due to FK dependencies:
///   1. BuildingDocuments (no FK dependencies)
///   2. Buildings       (optional FK → BuildingDocuments)
///   3. PropertyUnits   (FK → Buildings)
///   4. Persons         (no FK dependencies)
///   5. Households      (FK → PropertyUnits, optional FK → Persons)
///   6. PersonPropertyRelations (FK → Persons, FK → PropertyUnits)
///   7. Surveys         (FK → Buildings, FK → PropertyUnits)
///   8. Claims          (FK → PropertyUnits, optional FK → Persons)
///   9. Evidence        (FK → Persons, FK → PersonPropertyRelations, FK → Claims)
///
/// Each step uses a mapping dictionary (OriginalEntityId → ProductionId) to resolve
/// cross-references from the .uhc package to production FKs.
///
/// Record ID formats:
///   - Buildings: 17-digit geographic ID (GG-DD-SS-CCC-NNN-BBBBB) — composed by Building.Create()
///   - PropertyUnits: Building ID + 3-digit unit number — composed by PropertyUnit.Create()
///   - Claims: CL-YYYY-NNNNNN — generated by IClaimNumberGenerator
///   - Other entities (Persons, Households, Relations, Evidence, Surveys): UUID only, no Record ID.
/// </summary>
public class CommitService : ICommitService
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IStagingRepository<StagingBuilding> _stagingBuildingRepo;
    private readonly IStagingRepository<StagingBuildingDocument> _stagingBuildingDocRepo;
    private readonly IStagingRepository<StagingPropertyUnit> _stagingPropertyUnitRepo;
    private readonly IStagingRepository<StagingPerson> _stagingPersonRepo;
    private readonly IStagingRepository<StagingHousehold> _stagingHouseholdRepo;
    private readonly IStagingRepository<StagingPersonPropertyRelation> _stagingRelationRepo;
    private readonly IStagingRepository<StagingEvidence> _stagingEvidenceRepo;
    private readonly IStagingRepository<StagingEvidenceRelation> _stagingEvidenceRelationRepo;
    private readonly IStagingRepository<StagingIdentificationDocument> _stagingIdDocRepo;
    private readonly IStagingRepository<StagingClaim> _stagingClaimRepo;
    private readonly IStagingRepository<StagingSurvey> _stagingSurveyRepo;
    private readonly IImportPackageRepository _importPackageRepository;
    private readonly IClaimNumberGenerator _claimNumberGenerator;
    private readonly ICaseNumberGenerator _caseNumberGenerator;
    private readonly ISurveyReferenceCodeGenerator _surveyRefCodeGenerator;
    private readonly IImportService _importService;
    private readonly IFileStorageService _fileStorageService;
    private readonly IGeometryConverter _geometryConverter;
    private readonly ImportPipelineSettings _settings;
    private readonly ILogger<CommitService> _logger;

    // ID mapping: OriginalEntityId (from .uhc) → Production Entity Id
    private readonly Dictionary<Guid, Guid> _idMap = new();

    public CommitService(
        IUnitOfWork unitOfWork,
        IStagingRepository<StagingBuilding> stagingBuildingRepo,
        IStagingRepository<StagingBuildingDocument> stagingBuildingDocRepo,
        IStagingRepository<StagingPropertyUnit> stagingPropertyUnitRepo,
        IStagingRepository<StagingPerson> stagingPersonRepo,
        IStagingRepository<StagingHousehold> stagingHouseholdRepo,
        IStagingRepository<StagingPersonPropertyRelation> stagingRelationRepo,
        IStagingRepository<StagingEvidence> stagingEvidenceRepo,
        IStagingRepository<StagingEvidenceRelation> stagingEvidenceRelationRepo,
        IStagingRepository<StagingIdentificationDocument> stagingIdDocRepo,
        IStagingRepository<StagingClaim> stagingClaimRepo,
        IStagingRepository<StagingSurvey> stagingSurveyRepo,
        IImportPackageRepository importPackageRepository,
        IClaimNumberGenerator claimNumberGenerator,
        ICaseNumberGenerator caseNumberGenerator,
        ISurveyReferenceCodeGenerator surveyRefCodeGenerator,
        IImportService importService,
        IFileStorageService fileStorageService,
        IGeometryConverter geometryConverter,
        IOptions<ImportPipelineSettings> settings,
        ILogger<CommitService> logger)
    {
        _unitOfWork = unitOfWork;
        _stagingBuildingRepo = stagingBuildingRepo;
        _stagingBuildingDocRepo = stagingBuildingDocRepo;
        _stagingPropertyUnitRepo = stagingPropertyUnitRepo;
        _stagingPersonRepo = stagingPersonRepo;
        _stagingHouseholdRepo = stagingHouseholdRepo;
        _stagingRelationRepo = stagingRelationRepo;
        _stagingEvidenceRepo = stagingEvidenceRepo;
        _stagingEvidenceRelationRepo = stagingEvidenceRelationRepo;
        _stagingIdDocRepo = stagingIdDocRepo;
        _stagingClaimRepo = stagingClaimRepo;
        _stagingSurveyRepo = stagingSurveyRepo;
        _importPackageRepository = importPackageRepository;
        _claimNumberGenerator = claimNumberGenerator;
        _caseNumberGenerator = caseNumberGenerator;
        _surveyRefCodeGenerator = surveyRefCodeGenerator;
        _importService = importService;
        _fileStorageService = fileStorageService;
        _geometryConverter = geometryConverter;
        _settings = settings.Value;
        _logger = logger;
    }

    /// <inheritdoc />
    public async Task<CommitReportDto> CommitAsync(
        Guid importPackageId,
        Guid committedByUserId,
        CancellationToken cancellationToken = default)
    {
        _idMap.Clear();

        var report = new CommitReportDto
        {
            ImportPackageId = importPackageId,
            CommittedByUserId = committedByUserId,
            CommittedAtUtc = DateTime.UtcNow
        };

        var package = await _importPackageRepository.GetByIdAsync(importPackageId, cancellationToken)
            ?? throw new InvalidOperationException($"Package {importPackageId} not found.");

        report.PackageNumber = package.PackageNumber;

        // Pre-populate ID map from already-committed staging records (for re-commit scenarios).
        // When a partial commit succeeded, some staging entities already have CommittedEntityId set.
        // These won't be re-committed (GetApprovedForCommitAsync skips them), but child entities
        // (e.g. Claims referencing a PropertyUnit) still need their FK resolved via _idMap.
        await PrePopulateIdMapFromCommittedAsync(importPackageId, cancellationToken);

        // Clear change tracker to ensure no stale dirty entities from prior operations
        _unitOfWork.DetachAllEntities();

        // Execute the entire commit in a transaction
        await _unitOfWork.ExecuteInTransactionAsync(async () =>
        {
            // Commit in FK-dependency order
            await CommitBuildingsAsync(importPackageId, committedByUserId, report, cancellationToken);
            await CommitBuildingDocumentsAsync(importPackageId, committedByUserId, report, cancellationToken);
            await CommitPropertyUnitsAsync(importPackageId, committedByUserId, report, cancellationToken);
            await PopulateMergeRedirectsAsync("PropertyUnit", importPackageId, cancellationToken);
            await CommitPersonsAsync(importPackageId, committedByUserId, report, cancellationToken);
            await PopulateMergeRedirectsAsync("Person", importPackageId, cancellationToken);
            await CommitHouseholdsAsync(importPackageId, committedByUserId, report, cancellationToken);
            await CommitPersonPropertyRelationsAsync(importPackageId, committedByUserId, report, cancellationToken);
            await CommitSurveysAsync(importPackageId, committedByUserId, report, cancellationToken);
            await CommitClaimsAsync(importPackageId, committedByUserId, report, cancellationToken);
            await CommitEvidenceAsync(importPackageId, committedByUserId, report, cancellationToken);
            await CommitIdentificationDocumentsAsync(importPackageId, committedByUserId, report, cancellationToken);

            // Link Cases — runs last so all entities are resolved
            await LinkCasesAsync(importPackageId, committedByUserId, report, cancellationToken);
        }, cancellationToken);

        // Update aggregate counts
        report.TotalRecordsCommitted =
            report.BuildingDocuments.Committed + report.Buildings.Committed +
            report.PropertyUnits.Committed +
            report.Persons.Committed + report.Households.Committed +
            report.PersonPropertyRelations.Committed + report.Evidences.Committed +
            report.IdentificationDocuments.Committed +
            report.Claims.Committed + report.Surveys.Committed;

        report.TotalRecordsFailed =
            report.BuildingDocuments.Failed + report.Buildings.Failed +
            report.PropertyUnits.Failed +
            report.Persons.Failed + report.Households.Failed +
            report.PersonPropertyRelations.Failed + report.Evidences.Failed +
            report.IdentificationDocuments.Failed +
            report.Claims.Failed + report.Surveys.Failed;

        report.TotalRecordsApproved =
            report.BuildingDocuments.Approved + report.Buildings.Approved +
            report.PropertyUnits.Approved +
            report.Persons.Approved + report.Households.Approved +
            report.PersonPropertyRelations.Approved + report.Evidences.Approved +
            report.IdentificationDocuments.Approved +
            report.Claims.Approved + report.Surveys.Approved;

        report.Status = report.IsFullySuccessful
            ? ImportStatus.Completed.ToString()
            : (report.TotalRecordsCommitted > 0 ? ImportStatus.PartiallyCompleted.ToString() : ImportStatus.Failed.ToString());

        return report;
    }

    /// <inheritdoc />
    public async Task<string> ArchivePackageAsync(
        Guid importPackageId,
        Guid committedByUserId,
        CancellationToken cancellationToken = default)
    {
        var package = await _importPackageRepository.GetByIdAsync(importPackageId, cancellationToken)
            ?? throw new InvalidOperationException($"Package {importPackageId} not found.");

        // Resolve source path: prefer UploadedFilePath (set during upload), fallback to convention
        string? sourceFilePath = null;

        if (!string.IsNullOrWhiteSpace(package.UploadedFilePath) && File.Exists(package.UploadedFilePath))
        {
            sourceFilePath = package.UploadedFilePath;
        }
        else
        {
            // Fallback: search in package storage directory
            var storagePath = Path.GetFullPath(_settings.PackageStoragePath);
            if (Directory.Exists(storagePath))
            {
                sourceFilePath = Directory.GetFiles(storagePath, $"*{package.PackageId:N}*")
                    .FirstOrDefault();

                sourceFilePath ??= Directory.GetFiles(storagePath, $"*{Path.GetFileNameWithoutExtension(package.FileName)}*")
                    .FirstOrDefault();
            }
        }

        if (sourceFilePath == null || !File.Exists(sourceFilePath))
        {
            _logger.LogWarning(
                "Source .uhc file not found for package {PackageId}. " +
                "UploadedFilePath='{UploadedFilePath}', skipping archive.",
                package.PackageId, package.UploadedFilePath);
            return string.Empty;
        }

        var archivePath = await _importService.ArchivePackageAsync(
            sourceFilePath, package.PackageId, cancellationToken);

        return archivePath;
    }

    /// <summary>
    /// Populate _idMap with merge redirect mappings for resolved conflicts.
    ///
    /// When a conflict is resolved via Merge, the discarded entity's OriginalEntityId
    /// must map to the same production ID as the master entity. This ensures that
    /// other staging entities (e.g. StagingClaim referencing a merged StagingPropertyUnit)
    /// can resolve their FK references correctly during commit.
    ///
    /// Cross-batch: discarded is staging, master is production → _idMap[discarded] = production.Id
    /// Within-batch: discarded is staging, master is staging (already committed) → _idMap[discarded] = _idMap[master]
    /// </summary>

    /// <summary>
    /// Pre-populate the ID map from staging records that were already committed
    /// in a previous (partial) commit attempt. This ensures that child entities
    /// (e.g. Claims referencing an already-committed PropertyUnit) can still
    /// resolve their FK references via _idMap during re-commit.
    /// </summary>
    private async Task PrePopulateIdMapFromCommittedAsync(
        Guid importPackageId, CancellationToken ct)
    {
        var committedBuildingDocs = await _stagingBuildingDocRepo.GetCommittedAsync(importPackageId, ct);
        foreach (var d in committedBuildingDocs)
            _idMap.TryAdd(d.OriginalEntityId, d.CommittedEntityId!.Value);

        var committedBuildings = await _stagingBuildingRepo.GetCommittedAsync(importPackageId, ct);
        foreach (var b in committedBuildings)
            _idMap.TryAdd(b.OriginalEntityId, b.CommittedEntityId!.Value);

        var committedUnits = await _stagingPropertyUnitRepo.GetCommittedAsync(importPackageId, ct);
        foreach (var u in committedUnits)
            _idMap.TryAdd(u.OriginalEntityId, u.CommittedEntityId!.Value);

        var committedPersons = await _stagingPersonRepo.GetCommittedAsync(importPackageId, ct);
        foreach (var p in committedPersons)
            _idMap.TryAdd(p.OriginalEntityId, p.CommittedEntityId!.Value);

        var committedHouseholds = await _stagingHouseholdRepo.GetCommittedAsync(importPackageId, ct);
        foreach (var h in committedHouseholds)
            _idMap.TryAdd(h.OriginalEntityId, h.CommittedEntityId!.Value);

        var committedRelations = await _stagingRelationRepo.GetCommittedAsync(importPackageId, ct);
        foreach (var r in committedRelations)
            _idMap.TryAdd(r.OriginalEntityId, r.CommittedEntityId!.Value);

        var committedSurveys = await _stagingSurveyRepo.GetCommittedAsync(importPackageId, ct);
        foreach (var s in committedSurveys)
            _idMap.TryAdd(s.OriginalEntityId, s.CommittedEntityId!.Value);

        var committedClaims = await _stagingClaimRepo.GetCommittedAsync(importPackageId, ct);
        foreach (var c in committedClaims)
            _idMap.TryAdd(c.OriginalEntityId, c.CommittedEntityId!.Value);

        var committedEvidence = await _stagingEvidenceRepo.GetCommittedAsync(importPackageId, ct);
        foreach (var e in committedEvidence)
            _idMap.TryAdd(e.OriginalEntityId, e.CommittedEntityId!.Value);

        if (_idMap.Count > 0)
            _logger.LogInformation(
                "Pre-populated ID map with {Count} already-committed staging records for re-commit",
                _idMap.Count);
    }

    private async Task PopulateMergeRedirectsAsync(
        string entityType, Guid importPackageId, CancellationToken ct)
    {
        var mergedConflicts = await _unitOfWork.ConflictResolutions
            .GetResolvedMergesForPackageAsync(importPackageId, entityType, ct);

        foreach (var conflict in mergedConflicts)
        {
            var masterId = conflict.MergedEntityId!.Value;
            var discardedId = conflict.DiscardedEntityId!.Value;

            // Skip if discarded is already in the map
            if (_idMap.ContainsKey(discardedId))
                continue;

            if (_idMap.TryGetValue(masterId, out var productionId))
            {
                // Within-batch: master was committed → redirect discarded to same production ID
                _idMap[discardedId] = productionId;
                _logger.LogDebug(
                    "Merge redirect (within-batch): {Discarded} → {Production} (via master {Master})",
                    discardedId, productionId, masterId);
            }
            else
            {
                // Cross-batch: masterId IS the production ID (not in _idMap because it wasn't staged)
                _idMap[discardedId] = masterId;
                _logger.LogDebug(
                    "Merge redirect (cross-batch): {Discarded} → {Production}",
                    discardedId, masterId);
            }
        }
    }

    /// <summary>
    /// Commit building documents (photos/PDFs) to production.
    /// FK to Buildings — committed after buildings so BuildingDocument.BuildingId can be resolved.
    /// Supports attachment deduplication by SHA-256 hash.
    /// </summary>
    private async Task CommitBuildingDocumentsAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingBuildingDocRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.BuildingDocuments.EntityType = "BuildingDocument";
        report.BuildingDocuments.Approved = approved.Count;

        if (approved.Count == 0) return;

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                // Attachment deduplication by SHA-256 hash
                var filePath = staging.FilePath;
                if (!string.IsNullOrEmpty(staging.FileHash))
                {
                    var existingDoc = await _unitOfWork.BuildingDocuments
                        .GetByFileHashAsync(staging.FileHash, ct);

                    if (existingDoc != null)
                    {
                        filePath = existingDoc.FilePath;
                        report.DuplicateAttachmentsFound++;
                        report.DeduplicationBytesSaved += staging.FileSizeBytes;

                        _logger.LogInformation(
                            "Deduplicated building document file {Hash} — reusing {ExistingPath}",
                            staging.FileHash, filePath);
                    }
                }

                // Resolve parent building via _idMap
                if (!_idMap.TryGetValue(staging.OriginalBuildingId, out var prodBuildingId))
                {
                    _logger.LogWarning(
                        "BuildingDocument {OriginalId} references unknown building {OriginalBuildingId} — skipping",
                        staging.OriginalEntityId, staging.OriginalBuildingId);
                    report.BuildingDocuments.Failed++;
                    continue;
                }

                var document = BuildingDocument.Create(
                    buildingId: prodBuildingId,
                    description: staging.Description,
                    originalFileName: staging.OriginalFileName,
                    filePath: filePath,
                    fileSizeBytes: staging.FileSizeBytes,
                    mimeType: staging.MimeType,
                    fileHash: staging.FileHash,
                    createdByUserId: userId);

                await _unitOfWork.BuildingDocuments.AddAsync(document, ct);

                _idMap[staging.OriginalEntityId] = document.Id;
                staging.SetCommittedEntityId(document.Id);
                await _stagingBuildingDocRepo.UpdateAsync(staging, ct);

                report.BuildingDocuments.Committed++;
                report.BuildingDocuments.IdMappings[staging.OriginalEntityId] = document.Id;

                _logger.LogDebug(
                    "Committed BuildingDocument {OriginalId} → {ProductionId}",
                    staging.OriginalEntityId, document.Id);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit BuildingDocument {OriginalId}", staging.OriginalEntityId);
                report.BuildingDocuments.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "BuildingDocument",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    /// <summary>
    /// Commit buildings to production.
    /// Building Record ID (BuildingId) is a 17-digit geographic hierarchy code
    /// composed automatically by Building.Create() from the administrative codes
    /// (GovernorateCode + DistrictCode + SubDistrictCode + CommunityCode +
    /// NeighborhoodCode + BuildingNumber). No external sequence needed.
    /// Building Record ID format: GG-DD-SS-CCC-NNN-BBBBB.
    /// </summary>
    private async Task CommitBuildingsAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingBuildingRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.Buildings.EntityType = "Building";
        report.Buildings.Approved = approved.Count;

        if (approved.Count == 0) return;

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                // Compose the 17-digit BuildingId from geographic codes
                var buildingIdCode = $"{staging.GovernorateCode}{staging.DistrictCode}" +
                    $"{staging.SubDistrictCode}{staging.CommunityCode}" +
                    $"{staging.NeighborhoodCode}{staging.BuildingNumber}";

                // Check if a building with this BuildingId already exists in production
                // (e.g., from a previous package covering the same building)
                var existingBuilding = await _unitOfWork.Buildings
                    .GetByBuildingIdAsync(buildingIdCode, ct);

                if (existingBuilding != null)
                {
                    // Skip update if building is locked — still map the ID for dependent entities
                    if (existingBuilding.IsLocked)
                    {
                        _logger.LogWarning(
                            "Building {BuildingId} is locked — skipping field survey update. Staging {OriginalId} mapped to existing {ProductionId}.",
                            buildingIdCode, staging.OriginalEntityId, existingBuilding.Id);

                        _idMap[staging.OriginalEntityId] = existingBuilding.Id;
                        staging.SetCommittedEntityId(existingBuilding.Id);
                        await _stagingBuildingRepo.UpdateAsync(staging, ct);
                        report.Buildings.Committed++;
                        report.Buildings.IdMappings[staging.OriginalEntityId] = existingBuilding.Id;
                        continue;
                    }

                    // Update existing building with field survey data
                    // (preserves BuildingId, admin codes, geometry, and coordinates)
                    existingBuilding.UpdateFromFieldSurvey(
                        buildingType: staging.BuildingType,
                        status: staging.Status,
                        numberOfPropertyUnits: staging.NumberOfPropertyUnits,
                        numberOfApartments: staging.NumberOfApartments,
                        numberOfShops: staging.NumberOfShops,
                        notes: staging.Notes,
                        modifiedByUserId: userId);

                    await _unitOfWork.Buildings.UpdateAsync(existingBuilding, ct);

                    _idMap[staging.OriginalEntityId] = existingBuilding.Id;
                    staging.SetCommittedEntityId(existingBuilding.Id);
                    await _stagingBuildingRepo.UpdateAsync(staging, ct);

                    report.Buildings.Committed++;
                    report.Buildings.IdMappings[staging.OriginalEntityId] = existingBuilding.Id;

                    _logger.LogInformation(
                        "Building {OriginalId} updated existing production building {ProductionId} (BuildingId: {BuildingId})",
                        staging.OriginalEntityId, existingBuilding.Id, buildingIdCode);
                    continue;
                }

                // No existing building — create a new one
                var building = Building.Create(
                    governorateCode: staging.GovernorateCode,
                    districtCode: staging.DistrictCode,
                    subDistrictCode: staging.SubDistrictCode,
                    communityCode: staging.CommunityCode,
                    neighborhoodCode: staging.NeighborhoodCode,
                    buildingNumber: staging.BuildingNumber,
                    governorateName: staging.GovernorateName ?? string.Empty,
                    districtName: staging.DistrictName ?? string.Empty,
                    subDistrictName: staging.SubDistrictName ?? string.Empty,
                    communityName: staging.CommunityName ?? string.Empty,
                    neighborhoodName: staging.NeighborhoodName ?? string.Empty,
                    buildingType: staging.BuildingType,
                    status: staging.Status,
                    createdByUserId: userId);

                building.UpdateUnitCounts(
                    staging.NumberOfPropertyUnits,
                    staging.NumberOfApartments,
                    staging.NumberOfShops,
                    userId);

                building.UpdateDetails(
                    staging.Notes,
                    userId);

                if (staging.BuildingGeometryWkt != null)
                {
                    var geometry = _geometryConverter.ParseWkt(staging.BuildingGeometryWkt);
                    building.SetGeometry(geometry, userId);
                }

                if (staging.Latitude.HasValue && staging.Longitude.HasValue)
                {
                    var fallbackPoint = _geometryConverter.CreatePoint(
                        (double)staging.Longitude.Value, (double)staging.Latitude.Value);
                    building.SetCoordinates(staging.Latitude.Value, staging.Longitude.Value, userId, fallbackPoint);
                }

                await _unitOfWork.Buildings.AddAsync(building, ct);

                _idMap[staging.OriginalEntityId] = building.Id;
                staging.SetCommittedEntityId(building.Id);
                await _stagingBuildingRepo.UpdateAsync(staging, ct);

                report.Buildings.Committed++;
                report.Buildings.IdMappings[staging.OriginalEntityId] = building.Id;

                _logger.LogDebug(
                    "Committed Building {OriginalId} → {ProductionId} (BuildingId: {BuildingId})",
                    staging.OriginalEntityId, building.Id, building.BuildingId);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit Building {OriginalId}", staging.OriginalEntityId);
                report.Buildings.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "Building",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    /// <summary>
    /// Commit property units to production.
    /// Property Unit ID is derived from parent Building ID + UnitIdentifier.
    /// Full format = BuildingId-UnitNumber (e.g. 01-01-02-003-001-00001-001).
    /// </summary>
    private async Task CommitPropertyUnitsAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingPropertyUnitRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.PropertyUnits.EntityType = "PropertyUnit";
        report.PropertyUnits.Approved = approved.Count;

        if (approved.Count == 0) return;

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                // Resolve parent building FK
                if (!_idMap.TryGetValue(staging.OriginalBuildingId, out var productionBuildingId))
                {
                    throw new InvalidOperationException(
                        $"Parent Building {staging.OriginalBuildingId} not found in ID map. " +
                        "Building must be committed before its property units.");
                }

                // Check if a property unit with this (BuildingId, UnitIdentifier) already exists
                // (e.g., from a previous package covering the same building and unit)
                var existingUnit = await _unitOfWork.PropertyUnits
                    .GetByBuildingAndIdentifierAsync(productionBuildingId, staging.UnitIdentifier, ct);

                if (existingUnit != null)
                {
                    // Reuse the existing production unit — just map the ID
                    _idMap[staging.OriginalEntityId] = existingUnit.Id;
                    staging.SetCommittedEntityId(existingUnit.Id);
                    await _stagingPropertyUnitRepo.UpdateAsync(staging, ct);

                    report.PropertyUnits.Committed++;
                    report.PropertyUnits.IdMappings[staging.OriginalEntityId] = existingUnit.Id;

                    _logger.LogInformation(
                        "PropertyUnit {OriginalId} reused existing production unit {ProductionId} (Building: {BuildingId}, Unit: {UnitId})",
                        staging.OriginalEntityId, existingUnit.Id, productionBuildingId, staging.UnitIdentifier);
                    continue;
                }

                // No existing unit — create a new one
                var unit = PropertyUnit.Create(
                    buildingId: productionBuildingId,
                    unitIdentifier: staging.UnitIdentifier,
                    unitType: staging.UnitType,
                    floorNumber: staging.FloorNumber,
                    createdByUserId: userId,
                    status: staging.Status,
                    numberOfRooms: staging.NumberOfRooms,
                    areaSquareMeters: staging.AreaSquareMeters,
                    description: staging.Description);

                await _unitOfWork.PropertyUnits.AddAsync(unit, ct);

                _idMap[staging.OriginalEntityId] = unit.Id;
                staging.SetCommittedEntityId(unit.Id);
                await _stagingPropertyUnitRepo.UpdateAsync(staging, ct);

                report.PropertyUnits.Committed++;
                report.PropertyUnits.IdMappings[staging.OriginalEntityId] = unit.Id;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit PropertyUnit {OriginalId}", staging.OriginalEntityId);
                report.PropertyUnits.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "PropertyUnit",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    private async Task CommitPersonsAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingPersonRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.Persons.EntityType = "Person";
        report.Persons.Approved = approved.Count;

        if (approved.Count == 0) return;

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                var person = Person.CreateWithFullInfo(
                    familyNameArabic: staging.FamilyNameArabic,
                    firstNameArabic: staging.FirstNameArabic,
                    fatherNameArabic: staging.FatherNameArabic,
                    motherNameArabic: staging.MotherNameArabic,
                    nationalId: staging.NationalId,
                    dateOfBirth: staging.DateOfBirth,
                    gender: staging.Gender,
                    nationality: staging.Nationality,
                    email: staging.Email,
                    mobileNumber: staging.MobileNumber,
                    phoneNumber: staging.PhoneNumber,
                    createdByUserId: userId);

                if (staging.IsContactPerson)
                    person.SetAsContactPerson(true, userId);

                await _unitOfWork.Persons.AddAsync(person, ct);

                _idMap[staging.OriginalEntityId] = person.Id;
                staging.SetCommittedEntityId(person.Id);
                await _stagingPersonRepo.UpdateAsync(staging, ct);

                report.Persons.Committed++;
                report.Persons.IdMappings[staging.OriginalEntityId] = person.Id;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit Person {OriginalId}", staging.OriginalEntityId);
                report.Persons.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "Person",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    private async Task CommitHouseholdsAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingHouseholdRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.Households.EntityType = "Household";
        report.Households.Approved = approved.Count;

        if (approved.Count == 0) return;

        // Load staging persons and relations once to resolve household memberships after each household is created.
        // Persons are committed before households (FK order), so their production IDs are already in _idMap.
        var stagingPersons = await _stagingPersonRepo.GetByPackageIdAsync(importPackageId, ct);
        var stagingRelations = await _stagingRelationRepo.GetByPackageIdAsync(importPackageId, ct);

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                if (!_idMap.TryGetValue(staging.OriginalPropertyUnitId, out var productionUnitId))
                {
                    throw new InvalidOperationException(
                        $"Parent PropertyUnit {staging.OriginalPropertyUnitId} not found in ID map.");
                }

                var household = Household.Create(
                    propertyUnitId: productionUnitId,
                    householdSize: staging.HouseholdSize,
                    maleCount: staging.MaleCount,
                    femaleCount: staging.FemaleCount,
                    adultCount: staging.AdultCount,
                    childCount: staging.ChildCount,
                    elderlyCount: staging.ElderlyCount,
                    disabledCount: staging.DisabledCount,
                    occupancyNature: staging.OccupancyNature.HasValue ? (OccupancyNature)staging.OccupancyNature.Value : null,
                    occupancyStartDate: staging.OccupancyStartDate,
                    notes: staging.Notes,
                    createdByUserId: userId);

                await _unitOfWork.Households.AddAsync(household, ct);

                // Use TryAdd: the mobile app may reuse the PropertyUnit UUID as the Household UUID.
                // If the key is already in _idMap (PropertyUnit mapping), preserve it — subsequent
                // entities (Relations, Surveys, Claims) must resolve the PropertyUnit, not the Household.
                _idMap.TryAdd(staging.OriginalEntityId, household.Id);
                staging.SetCommittedEntityId(household.Id);
                await _stagingHouseholdRepo.UpdateAsync(staging, ct);

                report.Households.Committed++;
                report.Households.IdMappings[staging.OriginalEntityId] = household.Id;

                // Assign committed persons to this household.
                // Primary path: StagingPerson.OriginalHouseholdId (set when mobile populates persons.household_id).
                // Fallback: infer members from PersonPropertyRelations pointing to the same property unit,
                // but only when there is exactly one household per unit (no ambiguity across multiple families).
                var members = stagingPersons
                    .Where(p => p.OriginalHouseholdId == staging.OriginalEntityId)
                    .ToList();

                if (members.Count == 0)
                {
                    var householdsForUnit = approved.Count(h => h.OriginalPropertyUnitId == staging.OriginalPropertyUnitId);
                    if (householdsForUnit == 1)
                    {
                        var personIdsInUnit = stagingRelations
                            .Where(r => r.OriginalPropertyUnitId == staging.OriginalPropertyUnitId)
                            .Select(r => r.OriginalPersonId)
                            .ToHashSet();

                        members = stagingPersons
                            .Where(p => personIdsInUnit.Contains(p.OriginalEntityId) && !p.OriginalHouseholdId.HasValue)
                            .ToList();
                    }
                }

                foreach (var stagingPerson in members)
                {
                    if (!_idMap.TryGetValue(stagingPerson.OriginalEntityId, out var prodPersonId))
                        continue;

                    var person = await _unitOfWork.Persons.GetByIdAsync(prodPersonId, ct);
                    if (person != null)
                    {
                        person.AssignToHousehold(household.Id, userId);
                        await _unitOfWork.Persons.UpdateAsync(person, ct);
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit Household {OriginalId}", staging.OriginalEntityId);
                report.Households.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "Household",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    private async Task CommitPersonPropertyRelationsAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingRelationRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.PersonPropertyRelations.EntityType = "PersonPropertyRelation";
        report.PersonPropertyRelations.Approved = approved.Count;

        if (approved.Count == 0) return;

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                if (!_idMap.TryGetValue(staging.OriginalPersonId, out var productionPersonId))
                    throw new InvalidOperationException(
                        $"Person {staging.OriginalPersonId} not found in ID map.");

                if (!_idMap.TryGetValue(staging.OriginalPropertyUnitId, out var productionUnitId))
                    throw new InvalidOperationException(
                        $"PropertyUnit {staging.OriginalPropertyUnitId} not found in ID map.");

                var relation = PersonPropertyRelation.Create(
                    personId: productionPersonId,
                    propertyUnitId: productionUnitId,
                    relationType: staging.RelationType,
                    occupancyType: staging.OccupancyType,
                    hasEvidence: staging.HasEvidence,
                    createdByUserId: userId);

                relation.UpdateRelationDetails(
                    relationType: staging.RelationType,
                    occupancyType: staging.OccupancyType,
                    hasEvidence: staging.HasEvidence,
                    ownershipShare: staging.OwnershipShare,
                    contractDetails: staging.ContractDetails,
                    notes: staging.Notes,
                    modifiedByUserId: userId);

                await _unitOfWork.PersonPropertyRelations.AddAsync(relation, ct);

                _idMap[staging.OriginalEntityId] = relation.Id;
                staging.SetCommittedEntityId(relation.Id);
                await _stagingRelationRepo.UpdateAsync(staging, ct);

                report.PersonPropertyRelations.Committed++;
                report.PersonPropertyRelations.IdMappings[staging.OriginalEntityId] = relation.Id;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit PersonPropertyRelation {OriginalId}", staging.OriginalEntityId);
                report.PersonPropertyRelations.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "PersonPropertyRelation",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    private async Task CommitSurveysAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingSurveyRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.Surveys.EntityType = "Survey";
        report.Surveys.Approved = approved.Count;

        if (approved.Count == 0) return;

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                if (!_idMap.TryGetValue(staging.OriginalBuildingId, out var productionBuildingId))
                    throw new InvalidOperationException(
                        $"Building {staging.OriginalBuildingId} not found in ID map.");

                Guid? productionPropertyUnitId = null;
                if (staging.OriginalPropertyUnitId.HasValue &&
                    _idMap.TryGetValue(staging.OriginalPropertyUnitId.Value, out var unitId))
                {
                    productionPropertyUnitId = unitId;
                }

                // Resolve field collector ID — verify it exists in Users table,
                // fall back to the importing user if the original collector is not found
                // (tablet user IDs from .uhc packages may not exist in production)
                var fieldCollectorId = userId;
                if (staging.OriginalFieldCollectorId.HasValue)
                {
                    var collector = await _unitOfWork.Users.GetByIdAsync(
                        staging.OriginalFieldCollectorId.Value, ct);
                    if (collector != null)
                        fieldCollectorId = collector.Id;
                    else
                        _logger.LogWarning(
                            "Field collector {CollectorId} not found in Users table for Survey {SurveyId}. " +
                            "Using importing user {UserId} as fallback.",
                            staging.OriginalFieldCollectorId.Value, staging.OriginalEntityId, userId);
                }

                var type = staging.Type ?? SurveyType.Field;
                var prefix = type == SurveyType.Office ? "OFC" : "ALG";
                var refCode = staging.ReferenceCode
                    ?? await _surveyRefCodeGenerator.GenerateNextAsync(prefix, ct);

                // Check if a survey with this ReferenceCode already exists in production
                // (e.g., from a previous package covering the same survey)
                if (refCode != null)
                {
                    var existingSurvey = await _unitOfWork.Surveys
                        .GetByReferenceCodeAsync(refCode, ct);

                    if (existingSurvey != null)
                    {
                        _idMap[staging.OriginalEntityId] = existingSurvey.Id;
                        staging.SetCommittedEntityId(existingSurvey.Id);
                        await _stagingSurveyRepo.UpdateAsync(staging, ct);

                        report.Surveys.Committed++;
                        report.Surveys.IdMappings[staging.OriginalEntityId] = existingSurvey.Id;

                        _logger.LogInformation(
                            "Survey {OriginalId} reused existing production survey {ProductionId} (ReferenceCode: {RefCode})",
                            staging.OriginalEntityId, existingSurvey.Id, refCode);
                        continue;
                    }
                }

                var survey = Survey.Create(
                    buildingId: productionBuildingId,
                    fieldCollectorId: fieldCollectorId,
                    type: type,
                    surveyDate: staging.SurveyDate,
                    propertyUnitId: productionPropertyUnitId,
                    createdByUserId: userId,
                    referenceCode: refCode);

                // Transfer survey details (GPS, notes, duration)
                survey.UpdateSurveyDetails(
                    staging.GpsCoordinates,
                    staging.Notes,
                    staging.DurationMinutes,
                    userId);

                // Resolve contact person from staging.
                // Production persons committed earlier in this transaction are not yet in the DB
                // (SaveChangesAsync runs only at the end), so GetByIdAsync would return null.
                // Use staging person data directly to build the full name snapshot.
                if (staging.OriginalContactPersonId.HasValue &&
                    _idMap.TryGetValue(staging.OriginalContactPersonId.Value, out var productionContactPersonId))
                {
                    var stagingContact = await _stagingPersonRepo.GetByPackageAndOriginalIdAsync(
                        importPackageId, staging.OriginalContactPersonId.Value, ct);

                    if (stagingContact != null)
                    {
                        var parts = new[] {
                            stagingContact.FirstNameArabic,
                            stagingContact.FatherNameArabic,
                            stagingContact.FamilyNameArabic
                        };
                        var fullName = string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
                        if (!string.IsNullOrWhiteSpace(stagingContact.MotherNameArabic))
                            fullName += $" ({stagingContact.MotherNameArabic})";
                        survey.SetContactPerson(productionContactPersonId, fullName, userId);
                    }
                }

                // Surveys arriving via .uhc are always finalized on the tablet before export.
                // MarkAsFinalized requires a contact person — only call it when one was resolved.
                if (survey.ContactPersonId.HasValue)
                    survey.MarkAsFinalized(userId);

                await _unitOfWork.Surveys.AddAsync(survey, ct);

                _idMap[staging.OriginalEntityId] = survey.Id;
                staging.SetCommittedEntityId(survey.Id);
                await _stagingSurveyRepo.UpdateAsync(staging, ct);

                report.Surveys.Committed++;
                report.Surveys.IdMappings[staging.OriginalEntityId] = survey.Id;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit Survey {OriginalId}", staging.OriginalEntityId);
                report.Surveys.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "Survey",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    /// <summary>
    /// Commit claims to production with Claim Number generation (CL-YYYY-NNNNNN).
    /// Claim ID format: CL-YYYY-NNNNNN via IClaimNumberGenerator.
    /// </summary>
    private async Task CommitClaimsAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingClaimRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.Claims.EntityType = "Claim";
        report.Claims.Approved = approved.Count;

        if (approved.Count == 0) return;

        // Pre-load staging relations for CaseStatus resolution by RelationType
        var stagingRelations = await _stagingRelationRepo.GetApprovedForCommitAsync(importPackageId, ct);
        var relationByPersonAndUnit = stagingRelations
            .GroupBy(r => (r.OriginalPersonId, r.OriginalPropertyUnitId))
            .ToDictionary(g => g.Key, g => g.First());

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                if (!_idMap.TryGetValue(staging.OriginalPropertyUnitId, out var productionUnitId))
                    throw new InvalidOperationException(
                        $"PropertyUnit {staging.OriginalPropertyUnitId} not found in ID map.");

                // Resolve primary claimant — required for claim creation
                if (!staging.OriginalPrimaryClaimantId.HasValue)
                    throw new InvalidOperationException(
                        $"Staging claim {staging.OriginalEntityId} has no PrimaryClaimantId. Claims require a claimant.");

                if (!_idMap.TryGetValue(staging.OriginalPrimaryClaimantId.Value, out var productionClaimantId))
                    throw new InvalidOperationException(
                        $"Person {staging.OriginalPrimaryClaimantId.Value} not found in ID map for claim {staging.OriginalEntityId}.");

                // Generate a proper claim number
                var claimNumber = await _claimNumberGenerator.GenerateNextClaimNumberAsync(ct);

                // Resolve originating survey if present
                Guid? productionSurveyId = null;
                if (staging.OriginalOriginatingSurveyId.HasValue &&
                    _idMap.TryGetValue(staging.OriginalOriginatingSurveyId.Value, out var surveyId))
                {
                    productionSurveyId = surveyId;
                }

                var claim = Claim.Create(
                    claimNumber: claimNumber,
                    propertyUnitId: productionUnitId,
                    primaryClaimantId: productionClaimantId,
                    claimType: staging.ClaimType,
                    claimSource: staging.ClaimSource,
                    createdByUserId: userId,
                    originatingSurveyId: productionSurveyId);

                // Transfer tenure contract, ownership share, and description from staging
                if (staging.TenureContractType.HasValue)
                    claim.UpdateTenureContract(staging.TenureContractType.Value, null, userId);

                if (staging.OwnershipShare.HasValue)
                    claim.UpdateOwnershipShare((int)staging.OwnershipShare.Value, userId);

                if (!string.IsNullOrWhiteSpace(staging.ClaimDescription))
                    claim.UpdateClaimDescription(staging.ClaimDescription, userId);

                // Claims from tablet → set lifecycle to Submitted
                claim.Submit(userId, userId);

                // Set CaseStatus based on the generating PersonPropertyRelation's RelationType
                if (staging.OriginalPrimaryClaimantId.HasValue &&
                    relationByPersonAndUnit.TryGetValue(
                        (staging.OriginalPrimaryClaimantId.Value, staging.OriginalPropertyUnitId),
                        out var stagingRelation))
                {
                    if (stagingRelation.RelationType == RelationType.Owner ||
                        stagingRelation.RelationType == RelationType.Heir)
                    {
                        claim.CloseCase(userId);
                    }
                }

                await _unitOfWork.Claims.AddAsync(claim, ct);

                _idMap[staging.OriginalEntityId] = claim.Id;
                staging.SetCommittedEntityId(claim.Id);
                await _stagingClaimRepo.UpdateAsync(staging, ct);

                report.Claims.Committed++;
                report.Claims.IdMappings[staging.OriginalEntityId] = claim.Id;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit Claim {OriginalId}", staging.OriginalEntityId);
                report.Claims.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "Claim",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    /// <summary>
    /// Commit evidence to production with SHA-256 attachment deduplication.
    /// Uses IEvidenceRepository.GetByFileHashAsync() for dedup lookup.
    /// </summary>
    private async Task CommitEvidenceAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingEvidenceRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.Evidences.EntityType = "Evidence";
        report.Evidences.Approved = approved.Count;

        if (approved.Count == 0) return;

        // Pre-load junction rows for many-to-many evidence-relation links (v1.8+)
        var allJunctionRows = await _stagingEvidenceRelationRepo.GetByPackageIdAsync(importPackageId, ct);
        var junctionByEvidence = allJunctionRows
            .GroupBy(r => r.OriginalEvidenceId)
            .ToDictionary(g => g.Key, g => g.ToList());

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                // Attachment deduplication by SHA-256 hash
                var filePath = staging.FilePath;
                if (!string.IsNullOrEmpty(staging.FileHash))
                {
                    // Check if evidence with this hash already exists in production
                    var existingEvidence = await _unitOfWork.Evidences
                        .GetByFileHashAsync(staging.FileHash, ct);

                    if (existingEvidence != null)
                    {
                        // Reuse existing file path — no need to store another copy
                        filePath = existingEvidence.FilePath;
                        report.DuplicateAttachmentsFound++;
                        report.DeduplicationBytesSaved += staging.FileSizeBytes;

                        _logger.LogInformation(
                            "Deduplicated evidence file {Hash} — reusing {ExistingPath}",
                            staging.FileHash, filePath);
                    }
                }

                var evidence = Evidence.Create(
                    evidenceType: staging.EvidenceType,
                    description: staging.Description,
                    originalFileName: staging.OriginalFileName,
                    filePath: filePath,
                    fileSizeBytes: staging.FileSizeBytes,
                    mimeType: staging.MimeType,
                    fileHash: staging.FileHash,
                    createdByUserId: userId);

                // Link evidence to person-property relations
                // Priority: junction table (many-to-many) > direct FK (legacy 1:1)
                junctionByEvidence.TryGetValue(staging.OriginalEntityId, out var junctionLinks);

                if (junctionLinks != null && junctionLinks.Count > 0)
                {
                    // v1.8+ path: create one EvidenceRelation per junction row
                    foreach (var link in junctionLinks)
                    {
                        if (_idMap.TryGetValue(link.OriginalPersonPropertyRelationId, out var prodRelId))
                        {
                            var evidenceRelation = EvidenceRelation.Create(
                                evidenceId: evidence.Id,
                                personPropertyRelationId: prodRelId,
                                linkedBy: userId);
                            await _unitOfWork.EvidenceRelations.AddAsync(evidenceRelation, ct);
                        }
                    }
                }
                else if (staging.OriginalPersonPropertyRelationId.HasValue &&
                    _idMap.TryGetValue(staging.OriginalPersonPropertyRelationId.Value, out var fallbackRelId))
                {
                    // Legacy fallback: direct FK on evidence row (v1.7 and earlier)
                    var evidenceRelation = EvidenceRelation.Create(
                        evidenceId: evidence.Id,
                        personPropertyRelationId: fallbackRelId,
                        linkedBy: userId);
                    await _unitOfWork.EvidenceRelations.AddAsync(evidenceRelation, ct);
                }

                if (staging.OriginalClaimId.HasValue &&
                    _idMap.TryGetValue(staging.OriginalClaimId.Value, out var prodClaimId))
                {
                    evidence.LinkToClaim(prodClaimId, userId);
                }

                await _unitOfWork.Evidences.AddAsync(evidence, ct);

                _idMap[staging.OriginalEntityId] = evidence.Id;
                staging.SetCommittedEntityId(evidence.Id);
                await _stagingEvidenceRepo.UpdateAsync(staging, ct);

                report.Evidences.Committed++;
                report.Evidences.IdMappings[staging.OriginalEntityId] = evidence.Id;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit Evidence {OriginalId}", staging.OriginalEntityId);
                report.Evidences.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "Evidence",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    /// <summary>
    /// Commit identification documents to production.
    /// </summary>
    private async Task CommitIdentificationDocumentsAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        var approved = await _stagingIdDocRepo.GetApprovedForCommitAsync(importPackageId, ct);
        report.IdentificationDocuments.EntityType = "IdentificationDocument";
        report.IdentificationDocuments.Approved = approved.Count;

        if (approved.Count == 0) return;

        for (var i = 0; i < approved.Count; i++)
        {
            var staging = approved[i];
            try
            {
                // Resolve person ID
                if (!_idMap.TryGetValue(staging.OriginalPersonId, out var prodPersonId))
                {
                    _logger.LogWarning(
                        "IdentificationDocument {OriginalId} references unknown Person {PersonId}, skipping",
                        staging.OriginalEntityId, staging.OriginalPersonId);
                    report.IdentificationDocuments.Failed++;
                    continue;
                }

                var doc = IdentificationDocument.Create(
                    documentType: staging.DocumentType,
                    description: staging.Description,
                    originalFileName: staging.OriginalFileName,
                    filePath: staging.FilePath,
                    fileSizeBytes: staging.FileSizeBytes,
                    mimeType: staging.MimeType,
                    fileHash: staging.FileHash,
                    personId: prodPersonId,
                    createdByUserId: userId);

                if (staging.DocumentIssuedDate.HasValue || staging.DocumentExpiryDate.HasValue ||
                    !string.IsNullOrEmpty(staging.IssuingAuthority) || !string.IsNullOrEmpty(staging.DocumentReferenceNumber) ||
                    !string.IsNullOrEmpty(staging.Notes))
                {
                    doc.UpdateMetadata(
                        issuedDate: staging.DocumentIssuedDate,
                        expiryDate: staging.DocumentExpiryDate,
                        issuingAuthority: staging.IssuingAuthority,
                        referenceNumber: staging.DocumentReferenceNumber,
                        notes: staging.Notes,
                        modifiedByUserId: userId);
                }

                await _unitOfWork.IdentificationDocuments.AddAsync(doc, ct);

                _idMap[staging.OriginalEntityId] = doc.Id;
                staging.SetCommittedEntityId(doc.Id);
                await _stagingIdDocRepo.UpdateAsync(staging, ct);

                report.IdentificationDocuments.Committed++;
                report.IdentificationDocuments.IdMappings[staging.OriginalEntityId] = doc.Id;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to commit IdentificationDocument {OriginalId}", staging.OriginalEntityId);
                report.IdentificationDocuments.Failed++;
                report.Errors.Add(new CommitErrorDto
                {
                    EntityType = "IdentificationDocument",
                    StagingEntityId = staging.Id,
                    OriginalEntityId = staging.OriginalEntityId,
                    ErrorMessage = ex.Message
                });
            }
        }
    }

    /// <summary>
    /// Link Cases to committed entities. Runs as the last step so all IDs are resolved.
    /// For each unique PropertyUnit touched by this import:
    ///   - Creates a Case if one doesn't exist
    ///   - Links all committed Surveys, Claims, and PersonPropertyRelations to the Case
    ///   - Auto-closes the Case if an ownership/heir claim was committed
    /// </summary>
    private async Task LinkCasesAsync(
        Guid importPackageId, Guid userId, CommitReportDto report, CancellationToken ct)
    {
        try
        {
            // Collect all production PropertyUnit IDs touched by this import
            // from committed surveys, claims, and relations
            var propertyUnitIds = new HashSet<Guid>();

            // From surveys
            var committedSurveys = await _stagingSurveyRepo.GetApprovedForCommitAsync(importPackageId, ct);
            foreach (var staging in committedSurveys)
            {
                if (staging.CommittedEntityId.HasValue && staging.OriginalPropertyUnitId.HasValue)
                {
                    if (_idMap.TryGetValue(staging.OriginalPropertyUnitId.Value, out var productionUnitId))
                        propertyUnitIds.Add(productionUnitId);
                }
            }

            // From claims
            var committedClaims = await _stagingClaimRepo.GetApprovedForCommitAsync(importPackageId, ct);
            foreach (var staging in committedClaims)
            {
                if (staging.CommittedEntityId.HasValue)
                {
                    if (_idMap.TryGetValue(staging.OriginalPropertyUnitId, out var productionUnitId))
                        propertyUnitIds.Add(productionUnitId);
                }
            }

            if (!propertyUnitIds.Any()) return;

            foreach (var propertyUnitId in propertyUnitIds)
            {
                try
                {
                    // Get or create Case for this PropertyUnit
                    var caseEntity = await _unitOfWork.Cases.GetByPropertyUnitIdAsync(propertyUnitId, ct);

                    if (caseEntity == null)
                    {
                        var caseNumber = await _caseNumberGenerator.GenerateNextCaseNumberAsync(ct);
                        caseEntity = Case.Create(caseNumber, propertyUnitId, userId);
                        await _unitOfWork.Cases.AddAsync(caseEntity, ct);
                        await _unitOfWork.SaveChangesAsync(ct);

                        _logger.LogInformation(
                            "Created Case {CaseNumber} for PropertyUnit {PropertyUnitId}",
                            caseNumber, propertyUnitId);
                    }

                    // Link surveys to Case
                    var surveys = await _unitOfWork.Surveys.GetByPropertyUnitAsync(propertyUnitId, ct);
                    foreach (var survey in surveys)
                    {
                        if (!survey.CaseId.HasValue)
                            survey.LinkToCase(caseEntity.Id, userId);
                    }

                    // Link claims to Case and check for ownership
                    var claims = await _unitOfWork.Claims.GetAllByPropertyUnitIdAsync(propertyUnitId, ct);
                    foreach (var claim in claims)
                    {
                        if (!claim.CaseId.HasValue)
                            claim.LinkToCase(caseEntity.Id, userId);

                        // Auto-close Case on ownership/heir claim
                        if (claim.ClaimType == ClaimType.OwnershipClaim)
                        {
                            caseEntity.Close(claim.Id, userId);
                            _logger.LogInformation(
                                "Case {CaseNumber} closed by ownership claim {ClaimNumber}",
                                caseEntity.CaseNumber, claim.ClaimNumber);
                        }
                    }

                    // Link PersonPropertyRelations to Case
                    var relations = await _unitOfWork.PersonPropertyRelations
                        .GetByPropertyUnitIdAsync(propertyUnitId, ct);
                    foreach (var relation in relations)
                    {
                        if (!relation.CaseId.HasValue)
                            relation.LinkToCase(caseEntity.Id, userId);
                    }

                    await _unitOfWork.SaveChangesAsync(ct);
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex,
                        "Failed to link Case for PropertyUnit {PropertyUnitId}. Import continues.",
                        propertyUnitId);
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Case linking failed for import {ImportPackageId}. Import data is unaffected.", importPackageId);
        }
    }

}