using TRRCMS.Domain.Common;
using TRRCMS.Domain.Enums;

namespace TRRCMS.Domain.Entities.Staging;

/// <summary>
/// Staging entity for Claim records from .uhc packages.
/// Mirrors the <see cref="Claim"/> production entity in an isolated staging area.
/// Subject to claim lifecycle validation (FR-D-4 Level 6):
/// - Claim status transitions must be valid
/// - Claims from tablets are mapped to <see cref="LifecycleStage.Submitted"/> on commit (FR-D-2)
/// - Each claim must reference a valid property unit and optionally a primary claimant
/// 
/// Referenced in UC-003 Stage 2 (S13).
/// </summary>
public class StagingClaim : BaseStagingEntity
{
    // ==================== RELATIONSHIPS (original UUIDs from .uhc) ====================

    /// <summary>
    /// Original PropertyUnit UUID from .uhc — not a FK to production PropertyUnits.
    /// Must exist in StagingPropertyUnits for the same ImportPackageId.
    /// </summary>
    public Guid OriginalPropertyUnitId { get; private set; }

    /// <summary>
    /// Original primary claimant Person UUID from .uhc.
    /// Should exist in StagingPersons for the same ImportPackageId.
    /// </summary>
    public Guid? OriginalPrimaryClaimantId { get; private set; }

    // ==================== CLAIM IDENTIFICATION ====================

    /// <summary>
    /// Tablet-generated claim number — maps to permanent Record ID after commit (FR-D-8).
    /// Optional in staging — auto-generated by handler when not provided.
    /// </summary>
    public string? ClaimNumber { get; private set; }

    // ==================== CLAIM CLASSIFICATION ====================

    /// <summary>Claim type classification (stored as string for .uhc flexibility).</summary>
    public string ClaimType { get; private set; }

    /// <summary>How the claim was created (FieldCollection, OfficeSubmission, etc.).</summary>
    public ClaimSource ClaimSource { get; private set; }

    /// <summary>Priority level for claim processing. Defaults to Normal.</summary>
    public CasePriority Priority { get; private set; }

    /// <summary>Current lifecycle stage. Optional — auto-set to DraftPendingSubmission during commit.</summary>
    public LifecycleStage? LifecycleStage { get; private set; }

    /// <summary>Claim status. Optional — auto-set to Draft during commit.</summary>
    public ClaimStatus? Status { get; private set; }

    // ==================== TENURE DETAILS ====================

    /// <summary>Type of tenure/contract associated with the claim.</summary>
    public TenureContractType? TenureContractType { get; private set; }

    /// <summary>Ownership percentage (0-100).</summary>
    public decimal? OwnershipShare { get; private set; }

    /// <summary>Date from which tenure/occupancy started — from command, optional.</summary>
    public DateTime? TenureStartDate { get; private set; }

    /// <summary>Date when tenure/occupancy ended — from command, optional.</summary>
    public DateTime? TenureEndDate { get; private set; }

    /// <summary>Target completion date — from command, optional.</summary>
    public DateTime? TargetCompletionDate { get; private set; }

    // ==================== NARRATIVE ====================

    /// <summary>Detailed description of the claim.</summary>
    public string? ClaimDescription { get; private set; }

    /// <summary>Legal basis for the claim.</summary>
    public string? LegalBasis { get; private set; }

    /// <summary>Supporting narrative or testimony.</summary>
    public string? SupportingNarrative { get; private set; }

    // ==================== EVIDENCE STATUS ====================

    /// <summary>Number of evidence items attached to this claim.</summary>
    public int EvidenceCount { get; private set; }

    /// <summary>Whether all required document types have been submitted.</summary>
    public bool AllRequiredDocumentsSubmitted { get; private set; }

    /// <summary>JSON array of missing required document types.</summary>
    public string? MissingDocuments { get; private set; }

    // ==================== VERIFICATION ====================

    /// <summary>Verification status. Optional — auto-set to Pending during commit.</summary>
    public VerificationStatus? VerificationStatus { get; private set; }

    /// <summary>Notes from the verification process.</summary>
    public string? VerificationNotes { get; private set; }

    // ==================== NOTES ====================

    /// <summary>Internal processing notes (visible to staff only).</summary>
    public string? ProcessingNotes { get; private set; }

    /// <summary>Public remarks (visible to claimant).</summary>
    public string? PublicRemarks { get; private set; }

    // ==================== CONSTRUCTORS ====================

    /// <summary>EF Core constructor.</summary>
    private StagingClaim() : base()
    {
        ClaimType = string.Empty;
    }

    // ==================== FACTORY METHOD ====================

    /// <summary>
    /// Create a new StagingClaim record from .uhc package data.
    /// Required parameters match CreateClaimCommand fields.
    /// </summary>
    public static StagingClaim Create(
        Guid importPackageId,
        Guid originalEntityId,
        Guid originalPropertyUnitId,
        string claimType,
        ClaimSource claimSource,
        // --- optional: from command ---
        Guid? originalPrimaryClaimantId = null,
        CasePriority priority = CasePriority.Normal,
        TenureContractType? tenureContractType = null,
        decimal? ownershipShare = null,
        DateTime? tenureStartDate = null,
        DateTime? tenureEndDate = null,
        DateTime? targetCompletionDate = null,
        string? claimDescription = null,
        string? legalBasis = null,
        string? supportingNarrative = null,
        string? processingNotes = null,
        string? publicRemarks = null,
        // --- optional: auto-generated / commit-time ---
        string? claimNumber = null,
        LifecycleStage? lifecycleStage = null,
        ClaimStatus? status = null,
        VerificationStatus? verificationStatus = null,
        int evidenceCount = 0,
        bool allRequiredDocumentsSubmitted = false,
        string? missingDocuments = null,
        string? verificationNotes = null)
    {
        var entity = new StagingClaim
        {
            OriginalPropertyUnitId = originalPropertyUnitId,
            OriginalPrimaryClaimantId = originalPrimaryClaimantId,
            ClaimNumber = claimNumber,
            ClaimType = claimType,
            ClaimSource = claimSource,
            Priority = priority,
            LifecycleStage = lifecycleStage,
            Status = status,
            TenureContractType = tenureContractType,
            OwnershipShare = ownershipShare,
            TenureStartDate = tenureStartDate,
            TenureEndDate = tenureEndDate,
            TargetCompletionDate = targetCompletionDate,
            ClaimDescription = claimDescription,
            LegalBasis = legalBasis,
            SupportingNarrative = supportingNarrative,
            EvidenceCount = evidenceCount,
            AllRequiredDocumentsSubmitted = allRequiredDocumentsSubmitted,
            MissingDocuments = missingDocuments,
            VerificationStatus = verificationStatus,
            VerificationNotes = verificationNotes,
            ProcessingNotes = processingNotes,
            PublicRemarks = publicRemarks
        };

        entity.InitializeStagingMetadata(importPackageId, originalEntityId);
        return entity;
    }
}
