using TRRCMS.Domain.Common;
using TRRCMS.Domain.Enums;

namespace TRRCMS.Domain.Entities.Staging;

/// <summary>
/// Staging entity for Claim records from .uhc packages.
/// Mirrors the <see cref="Claim"/> production entity in an isolated staging area.
/// Subject to claim lifecycle validation (FR-D-4 Level 6):
/// - Claim status transitions must be valid
/// - Claims from tablets are mapped to Submitted on commit (FR-D-2)
/// - Each claim must reference a valid property unit and optionally a primary claimant
///
/// Referenced in UC-003 Stage 2 (S13).
/// </summary>
public class StagingClaim : BaseStagingEntity
{
    // ==================== RELATIONSHIPS (original UUIDs from .uhc) ====================

    /// <summary>
    /// Original PropertyUnit UUID from .uhc — not a FK to production PropertyUnits.
    /// Must exist in StagingPropertyUnits for the same ImportPackageId.
    /// </summary>
    public Guid OriginalPropertyUnitId { get; private set; }

    /// <summary>
    /// Original primary claimant Person UUID from .uhc.
    /// Should exist in StagingPersons for the same ImportPackageId.
    /// </summary>
    public Guid? OriginalPrimaryClaimantId { get; private set; }

    // ==================== CLAIM IDENTIFICATION ====================

    /// <summary>
    /// Tablet-generated claim number — maps to permanent Record ID after commit (FR-D-8).
    /// Optional in staging — auto-generated by handler when not provided.
    /// </summary>
    public string? ClaimNumber { get; private set; }

    // ==================== CLAIM CLASSIFICATION ====================

    /// <summary>Claim type classification (stored as string for .uhc flexibility).</summary>
    public string ClaimType { get; private set; }

    /// <summary>How the claim was created (FieldCollection, OfficeSubmission, etc.).</summary>
    public ClaimSource ClaimSource { get; private set; }

    /// <summary>Case status. Optional — auto-set to Open during commit.</summary>
    public CaseStatus? CaseStatus { get; private set; }

    // ==================== TENURE DETAILS ====================

    /// <summary>Type of tenure/contract associated with the claim.</summary>
    public TenureContractType? TenureContractType { get; private set; }

    /// <summary>Ownership percentage (0-100).</summary>
    public decimal? OwnershipShare { get; private set; }

    // ==================== NARRATIVE ====================

    /// <summary>Detailed description of the claim.</summary>
    public string? ClaimDescription { get; private set; }

    // ==================== CONSTRUCTORS ====================

    /// <summary>EF Core constructor.</summary>
    private StagingClaim() : base()
    {
        ClaimType = string.Empty;
    }

    // ==================== FACTORY METHOD ====================

    /// <summary>
    /// Create a new StagingClaim record from .uhc package data.
    /// Required parameters match CreateClaimCommand fields.
    /// </summary>
    public static StagingClaim Create(
        Guid importPackageId,
        Guid originalEntityId,
        Guid originalPropertyUnitId,
        string claimType,
        ClaimSource claimSource,
        // --- optional: from command ---
        Guid? originalPrimaryClaimantId = null,
        TenureContractType? tenureContractType = null,
        decimal? ownershipShare = null,
        string? claimDescription = null,
        // --- optional: auto-generated / commit-time ---
        string? claimNumber = null,
        CaseStatus? caseStatus = null)
    {
        var entity = new StagingClaim
        {
            OriginalPropertyUnitId = originalPropertyUnitId,
            OriginalPrimaryClaimantId = originalPrimaryClaimantId,
            ClaimNumber = claimNumber,
            ClaimType = claimType,
            ClaimSource = claimSource,
            CaseStatus = caseStatus,
            TenureContractType = tenureContractType,
            OwnershipShare = ownershipShare,
            ClaimDescription = claimDescription
        };

        entity.InitializeStagingMetadata(importPackageId, originalEntityId);
        return entity;
    }
}
