// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TRRCMS.Infrastructure.Persistence;

#nullable disable

namespace TRRCMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260108123239_AddDocumentEntity")]
    partial class AddDocumentEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TRRCMS.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BuildingGeometryWkt")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommunityCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CommunityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DamageLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GovernorateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("GovernorateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Landmark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("NeighborhoodCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("NeighborhoodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("NumberOfApartments")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfFloors")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfPropertyUnits")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfShops")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubDistrictCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("SubDistrictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("YearOfConstruction")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .IsUnique();

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllRequiredDocumentsSubmitted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CertificateStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ClaimDescription")
                        .HasColumnType("text");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClaimSource")
                        .HasColumnType("integer");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConflictCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConflictResolutionStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DecisionByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionNotes")
                        .HasColumnType("text");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("FinalDecision")
                        .HasColumnType("text");

                    b.Property<bool>("HasConflicts")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LegalBasis")
                        .HasColumnType("text");

                    b.Property<int>("LifecycleStage")
                        .HasColumnType("integer");

                    b.Property<string>("MissingDocuments")
                        .HasColumnType("text");

                    b.Property<int?>("OwnershipShare")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrimaryClaimantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessingNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicRemarks")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SupportingNarrative")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TargetCompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TenureContractType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TenureEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TenureStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("text");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryClaimantId");

                    b.HasIndex("PropertyUnitId");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to Claim (if document supports a claim)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when record was created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("User ID who created this record");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when record was soft deleted");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("User ID who soft deleted this record");

                    b.Property<string>("DocumentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("SHA-256 hash of the document for integrity verification");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Document number/reference (e.g., Tabu number, ID number, contract number)");

                    b.Property<string>("DocumentTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Document title or description in Arabic");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Document type from controlled vocabulary (e.g., TabuGreen, RentalContract, NationalIdCard)");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to Evidence entity (the actual file/scan)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when document expires (if applicable)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag");

                    b.Property<bool>("IsLegallyValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Indicates if document is legally valid");

                    b.Property<bool>("IsNotarized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indicates if document is notarized");

                    b.Property<bool>("IsOriginal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Indicates if document is original or a copy");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indicates if document has been verified");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when document was issued");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Issuing authority/organization (e.g., Ministry of Interior, Aleppo Municipality)");

                    b.Property<string>("IssuingPlace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Place where document was issued");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when record was last modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("User ID who last modified this record");

                    b.Property<string>("LegalValidityNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Legal validity notes (why valid or invalid)");

                    b.Property<DateTime?>("NotarizationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Notarization date");

                    b.Property<string>("NotarizationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Notarization number");

                    b.Property<string>("NotaryOffice")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Notary office name/number");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Additional notes about this document");

                    b.Property<Guid?>("OriginalDocumentId")
                        .HasColumnType("uuid")
                        .HasComment("If copy, reference to original document (if in system)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to Person (if document belongs to a person)");

                    b.Property<Guid?>("PersonPropertyRelationId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to PersonPropertyRelation (if document proves a relation)");

                    b.Property<Guid?>("PropertyUnitId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to PropertyUnit (if document relates to property)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when document was verified");

                    b.Property<string>("VerificationNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Verification notes or comments");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasComment("Verification status (Pending, Verified, Rejected, RequiresAdditionalInfo)");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasComment("User who verified the document");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("IX_Documents_ClaimId");

                    b.HasIndex("DocumentNumber")
                        .HasDatabaseName("IX_Documents_DocumentNumber");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("IX_Documents_DocumentType");

                    b.HasIndex("EvidenceId")
                        .HasDatabaseName("IX_Documents_EvidenceId");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_Documents_ExpiryDate");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Documents_IsDeleted");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("IX_Documents_IsVerified");

                    b.HasIndex("OriginalDocumentId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_Documents_PersonId");

                    b.HasIndex("PersonPropertyRelationId")
                        .HasDatabaseName("IX_Documents_PersonPropertyRelationId");

                    b.HasIndex("PropertyUnitId")
                        .HasDatabaseName("IX_Documents_PropertyUnitId");

                    b.HasIndex("VerificationStatus")
                        .HasDatabaseName("IX_Documents_VerificationStatus");

                    b.HasIndex("DocumentType", "VerificationStatus")
                        .HasDatabaseName("IX_Documents_DocumentType_VerificationStatus");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to Claim (if evidence supports a claim)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Creation timestamp (UTC)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who created this record");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Deletion timestamp (UTC)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who deleted this record");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Document or evidence description");

                    b.Property<DateTime?>("DocumentExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the document expires (if applicable)");

                    b.Property<DateTime?>("DocumentIssuedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the document was issued (if applicable)");

                    b.Property<string>("DocumentReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Document reference number (if any)");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Evidence type (controlled vocabulary)");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("SHA-256 hash of the file for integrity verification");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("File path in storage system");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasComment("File size in bytes");

                    b.Property<bool>("IsCurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Indicates if this is the current/latest version");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Issuing authority or organization");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last modification timestamp (UTC)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who last modified this record");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("MIME type (e.g., image/jpeg, application/pdf)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Additional notes about this evidence");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Original filename as uploaded");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to Person (if evidence is linked to a person)");

                    b.Property<Guid?>("PersonPropertyRelationId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to PersonPropertyRelation (if evidence supports a relation)");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid")
                        .HasComment("Reference to previous version (if this is an updated version)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasComment("Concurrency token");

                    b.Property<int>("VersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasComment("Version number for document versioning");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("IX_Evidence_ClaimId");

                    b.HasIndex("DocumentExpiryDate")
                        .HasDatabaseName("IX_Evidence_DocumentExpiryDate");

                    b.HasIndex("EvidenceType")
                        .HasDatabaseName("IX_Evidence_EvidenceType");

                    b.HasIndex("IsCurrentVersion")
                        .HasDatabaseName("IX_Evidence_IsCurrentVersion");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Evidence_IsDeleted");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_Evidence_PersonId");

                    b.HasIndex("PersonPropertyRelationId")
                        .HasDatabaseName("IX_Evidence_PersonPropertyRelationId");

                    b.HasIndex("PreviousVersionId");

                    b.HasIndex("IsCurrentVersion", "IsDeleted")
                        .HasDatabaseName("IX_Evidence_IsCurrentVersion_IsDeleted");

                    b.ToTable("Evidences", (string)null);
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdultCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of adults (18-64 years)");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date of arrival at current location");

                    b.Property<int>("ChildCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of children (2-12 years)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Creation timestamp (UTC)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who created this record");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Deletion timestamp (UTC)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who deleted this record");

                    b.Property<string>("DisplacementReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Reason for displacement");

                    b.Property<int>("ElderlyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of elderly (65+ years)");

                    b.Property<int>("EmployedPersonsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of employed persons");

                    b.Property<int>("FemaleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of female members");

                    b.Property<string>("HeadOfHouseholdName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Name of head of household");

                    b.Property<Guid?>("HeadOfHouseholdPersonId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to Person (head of household)");

                    b.Property<int>("HouseholdSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total household size");

                    b.Property<int>("InfantCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of infants (under 2 years)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag");

                    b.Property<bool>("IsDisplaced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indicates if household is displaced");

                    b.Property<bool>("IsFemaleHeaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indicates if household is female-headed");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last modification timestamp (UTC)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who last modified this record");

                    b.Property<int>("MaleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of male members");

                    b.Property<int>("MinorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of minors/adolescents (13-17 years)");

                    b.Property<decimal?>("MonthlyIncomeEstimate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Estimated monthly income");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Household notes");

                    b.Property<string>("OriginLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Origin location if displaced");

                    b.Property<int>("OrphanCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of orphans");

                    b.Property<int>("PersonsWithDisabilitiesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of persons with disabilities");

                    b.Property<string>("PrimaryIncomeSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Primary income source");

                    b.Property<Guid>("PropertyUnitId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to PropertyUnit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasComment("Concurrency token");

                    b.Property<int>("SingleParentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of single parents");

                    b.Property<string>("SpecialNeeds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Special needs or circumstances");

                    b.Property<int>("UnemployedPersonsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of unemployed persons");

                    b.Property<int>("WidowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of widows");

                    b.HasKey("Id");

                    b.HasIndex("HeadOfHouseholdPersonId")
                        .HasDatabaseName("IX_Household_HeadOfHouseholdPersonId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Household_IsDeleted");

                    b.HasIndex("PropertyUnitId")
                        .HasDatabaseName("IX_Household_PropertyUnitId");

                    b.HasIndex("IsDisplaced", "IsDeleted")
                        .HasDatabaseName("IX_Household_IsDisplaced_IsDeleted");

                    b.ToTable("Households", (string)null);
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Creation timestamp (UTC)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who created this record");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Deletion timestamp (UTC)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who deleted this record");

                    b.Property<string>("FamilyNameArabic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Family/Last name in Arabic (اسم العائلة)");

                    b.Property<string>("FatherNameArabic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Father's name in Arabic (اسم الأب)");

                    b.Property<string>("FirstNameArabic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("First name in Arabic (الاسم الأول)");

                    b.Property<string>("FullNameEnglish")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Full name in English (optional)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Gender (controlled vocabulary: M/F)");

                    b.Property<bool>("HasIdentificationDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Flag indicating if ID document was uploaded");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to household (nullable)");

                    b.Property<bool>("IsContactPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indicates if this person is the main contact");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last modification timestamp (UTC)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who last modified this record");

                    b.Property<string>("MotherNameArabic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Mother's name in Arabic (اسم الأم)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("National ID or identification number");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Nationality (controlled vocabulary)");

                    b.Property<string>("PrimaryPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Primary phone number");

                    b.Property<string>("RelationshipToHead")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Relationship to head of household");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasComment("Concurrency token");

                    b.Property<string>("SecondaryPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Secondary phone number");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("integer")
                        .HasComment("Year of birth (integer)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("IX_Person_HouseholdId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Person_IsDeleted");

                    b.HasIndex("NationalId")
                        .HasDatabaseName("IX_Person_NationalId");

                    b.HasIndex("PrimaryPhoneNumber")
                        .HasDatabaseName("IX_Person_PrimaryPhoneNumber");

                    b.HasIndex("FirstNameArabic", "FatherNameArabic", "FamilyNameArabic")
                        .HasDatabaseName("IX_Person_FullNameArabic");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.PersonPropertyRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContractDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Contract or agreement details");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Creation timestamp (UTC)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who created this record");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Deletion timestamp (UTC)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who deleted this record");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("End date of the relation (for terminated relations)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Indicates if this relation is currently active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last modification timestamp (UTC)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("User who last modified this record");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Additional notes about this relation");

                    b.Property<decimal?>("OwnershipShare")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasComment("Ownership or occupancy share (0.0 to 1.0 for percentage)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to Person");

                    b.Property<Guid>("PropertyUnitId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to PropertyUnit");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Type of relation (owner, tenant, occupant, guest, heir, other, etc.)");

                    b.Property<string>("RelationTypeOtherDesc")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Description when relation type is 'Other'");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasComment("Concurrency token");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Start date of the relation");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PersonPropertyRelation_IsActive");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_PersonPropertyRelation_IsDeleted");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_PersonPropertyRelation_PersonId");

                    b.HasIndex("PropertyUnitId")
                        .HasDatabaseName("IX_PersonPropertyRelation_PropertyUnitId");

                    b.HasIndex("RelationType")
                        .HasDatabaseName("IX_PersonPropertyRelation_RelationType");

                    b.HasIndex("IsActive", "IsDeleted")
                        .HasDatabaseName("IX_PersonPropertyRelation_IsActive_IsDeleted");

                    b.HasIndex("PersonId", "PropertyUnitId")
                        .HasDatabaseName("IX_PersonPropertyRelation_PersonId_PropertyUnitId");

                    b.ToTable("PersonPropertyRelations", (string)null);
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.PropertyUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AreaSquareMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DamageLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasBalcony")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("NumberOfBathrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfHouseholds")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfRooms")
                        .HasColumnType("integer");

                    b.Property<string>("OccupancyNature")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OccupancyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SpecialFeatures")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TotalOccupants")
                        .HasColumnType("integer");

                    b.Property<string>("UnitIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId", "UnitIdentifier")
                        .IsUnique()
                        .HasDatabaseName("IX_PropertyUnits_BuildingId_UnitIdentifier");

                    b.ToTable("PropertyUnits", (string)null);
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActionsRequired")
                        .HasColumnType("text");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentsRequired")
                        .HasColumnType("text");

                    b.Property<int?>("EscalationLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpectedResponseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEscalation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreviousReferralId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReferralDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferralNotes")
                        .HasColumnType("text");

                    b.Property<string>("ReferralNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferralReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferralType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseNotes")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TargetResolutionHours")
                        .HasColumnType("integer");

                    b.Property<int>("ToRole")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ToUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("PreviousReferralId");

                    b.ToTable("Referral");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Claim", b =>
                {
                    b.HasOne("TRRCMS.Domain.Entities.Person", "PrimaryClaimant")
                        .WithMany()
                        .HasForeignKey("PrimaryClaimantId");

                    b.HasOne("TRRCMS.Domain.Entities.PropertyUnit", "PropertyUnit")
                        .WithMany()
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryClaimant");

                    b.Navigation("PropertyUnit");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Document", b =>
                {
                    b.HasOne("TRRCMS.Domain.Entities.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId");

                    b.HasOne("TRRCMS.Domain.Entities.Evidence", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TRRCMS.Domain.Entities.Document", "OriginalDocument")
                        .WithMany()
                        .HasForeignKey("OriginalDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TRRCMS.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TRRCMS.Domain.Entities.PersonPropertyRelation", "PersonPropertyRelation")
                        .WithMany()
                        .HasForeignKey("PersonPropertyRelationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TRRCMS.Domain.Entities.PropertyUnit", "PropertyUnit")
                        .WithMany()
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("Evidence");

                    b.Navigation("OriginalDocument");

                    b.Navigation("Person");

                    b.Navigation("PersonPropertyRelation");

                    b.Navigation("PropertyUnit");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("TRRCMS.Domain.Entities.Claim", "Claim")
                        .WithMany("Evidences")
                        .HasForeignKey("ClaimId");

                    b.HasOne("TRRCMS.Domain.Entities.Person", "Person")
                        .WithMany("Evidences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TRRCMS.Domain.Entities.PersonPropertyRelation", "PersonPropertyRelation")
                        .WithMany("Evidences")
                        .HasForeignKey("PersonPropertyRelationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TRRCMS.Domain.Entities.Evidence", "PreviousVersion")
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("Person");

                    b.Navigation("PersonPropertyRelation");

                    b.Navigation("PreviousVersion");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Household", b =>
                {
                    b.HasOne("TRRCMS.Domain.Entities.Person", "HeadOfHouseholdPerson")
                        .WithMany()
                        .HasForeignKey("HeadOfHouseholdPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TRRCMS.Domain.Entities.PropertyUnit", "PropertyUnit")
                        .WithMany("Households")
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HeadOfHouseholdPerson");

                    b.Navigation("PropertyUnit");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Person", b =>
                {
                    b.HasOne("TRRCMS.Domain.Entities.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Household");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.PersonPropertyRelation", b =>
                {
                    b.HasOne("TRRCMS.Domain.Entities.Person", "Person")
                        .WithMany("PropertyRelations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TRRCMS.Domain.Entities.PropertyUnit", "PropertyUnit")
                        .WithMany()
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("PropertyUnit");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.PropertyUnit", b =>
                {
                    b.HasOne("TRRCMS.Domain.Entities.Building", "Building")
                        .WithMany("PropertyUnits")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Referral", b =>
                {
                    b.HasOne("TRRCMS.Domain.Entities.Claim", "Claim")
                        .WithMany("Referrals")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRRCMS.Domain.Entities.Referral", "PreviousReferral")
                        .WithMany()
                        .HasForeignKey("PreviousReferralId");

                    b.Navigation("Claim");

                    b.Navigation("PreviousReferral");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Building", b =>
                {
                    b.Navigation("PropertyUnits");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Evidences");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Household", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.Person", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("PropertyRelations");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.PersonPropertyRelation", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("TRRCMS.Domain.Entities.PropertyUnit", b =>
                {
                    b.Navigation("Households");
                });
#pragma warning restore 612, 618
        }
    }
}
